### ISSUE TITLE
Color Classes

### ISSUE THREAD

**Issue by SherlockSec** [1nfos3c/Aleph#1]
The `bcolors` class, the `Colors` list and the `signs` class are present in both `Aleph.py` and `src/wordlist_manipulation.py`. As there is no reason for their presense in both files, porting these to `src/wordlist_manipulation.py` would be best. As everything from `src/wordlist_manipulation.py` is already being imported, there should be no major code changes.

**Comment by SherlockSec** [comment]
Issue fixed in PR #2

**Comment by 1nfos3c** [comment]
Thanks for your contribution!
