### ISSUE TITLE
print(help) is never reached

### ISSUE THREAD

**Issue by 1nfos3c** [1nfos3c/Aleph#11]
in Aleph.py the keyword argument is checked for being a URL like this:  
```isurl = re.search(r'https?://', keyword) # Checking if user input is a URL```  
To decide if it must be treated as a URL the following if statements are used:  
```if (isurl is not None):```  
&
```elif (isurl is None):```  
because isurl is always either ```None``` or not ```None``` the following else statement is never reached.

**Comment by b4llsec** [comment]
I will fix it
